application: flyingcapacitor
version: 1
api_version: 1
runtime: python

handlers:
- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images
  
- url: /css
  static_dir: static/css

- url: .*
  script: unlock.py





